language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
install:
    - pip install -r requirements.txt
    - pip install python-coveralls
script:
    - nosetests --with-coverage --cover-package=testvibe --cover-inclusive --cover-erase tests/
after_success:
    - coveralls
