#!/usr/bin/python

import argparse

import testvibe


class CMDHandler(object):

    args = None

    def __init__(self, args):
        self.args = args

    def execute(self):
        if self.args.cmd == 'startproject':
            # TODO(niklas9):
            # * initiate project
            pass
        elif self.args.cmd == 'run':
            # TODO(niklas9):
            # * initiate test run
            pass


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Testvibe control')
    subparsers = parser.add_subparsers()
    # startproject
    cmd_startproject = subparsers.add_parser('startproject',
                                             help='start a new project')
    cmd_startproject.add_argument('dir')
    cmd_startproject.set_defaults(cmd='startproject')
    # run
    cmd_run = subparsers.add_parser('run', help='initiate test run')
    cmd_run.add_argument('-p', '--parallel', default=1,
                         help='number of testsuites to run in parallel')
    cmd_run.add_argument('-v', '--verbosity', action='store_true',
                        help='verbosity level')
    cmd_run.set_defaults(cmd='run')
    parser.add_argument('-V', '--version', action='version',
                        version=testvibe.VERSION,
                        help='show program\'s version number and exit')
    cmd_handler = CMDHandler(parser.parse_args())
    cmd_handler.execute()
